import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "~/components/navbar/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Jester</title>
        <meta
          name="I'm your life companion"
          content="Generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />
      </main>
    </>
  );
};

export default Home;
